// <auto-generated> 由 AudioGroupGenerator 根据 AudioMixer 生成，请勿手动修改 </auto-generated>
// 如果这是首次使用，请通过菜单 Tools > CFramework > Generate AudioGroup Enum 生成
using System.ComponentModel;

namespace CFramework
{
    /// <summary>
    ///     音频分组枚举（编辑器自动生成）
    ///     <para>值 = 路径哈希(Animator.StringToHash)，用于运行时 O(1) 查找</para>
    ///     <para>生成菜单：Tools > CFramework > Generate AudioGroup Enum</para>
    /// </summary>
    public enum AudioGroup
    {
        [Description("Master")]         Master = -1969408504,
        [Description("Master/BGM")]     Master_BGM = 1521745271,
        [Description("Master/SFX")]     Master_SFX = -846285009,
        [Description("Master/Voice")]   Master_Voice = 537193887,
        [Description("Master/Ambient")] Master_Ambient = -1659809336,
    }
}
