using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using CFramework.Editor.Configs;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEngine;

namespace CFramework.Editor.Generators
{
    /// <summary>
    ///     Addressables 资源常量生成器
    ///     根据 Addressables Group 分组生成静态常量类
    /// </summary>
    public static class AddressableConstantsGenerator
    {
        #region 配置常量

        private const string AutoGeneratedHeader = "// <auto-generated>\n" +
                                                   "//    此代码由 CFramework AddressableConstantsGenerator 自动生成。\n" +
                                                   "//    对此文件的更改可能导致错误的行为，并且会在重新生成时丢失。\n" +
                                                   "// </auto-generated>\n";

        #endregion

        #region 公开方法

        /// <summary>
        ///     使用默认配置生成常量文件
        /// </summary>
        [MenuItem("CFramework/Addressables/生成资源常量", false, 101)]
        public static void Generate()
        {
            var config = AddressableConfig.GetOrCreateInstance();
            Generate(config);
        }

        /// <summary>
        ///     使用指定配置生成常量文件
        /// </summary>
        /// <param name="config">Addressables 配置</param>
        public static void Generate(AddressableConfig config)
        {
            if (config == null)
            {
                Debug.LogError("[AddressableConstantsGenerator] 配置为空，无法生成常量文件");
                return;
            }

            var settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null)
            {
                Debug.LogWarning("[AddressableConstantsGenerator] 未找到 Addressable Asset Settings，跳过生成");
                return;
            }

            try
            {
                // 收集所有分组数据
                var groups = CollectGroups(settings, config);

                if (groups.Count == 0)
                {
                    Debug.LogWarning("[AddressableConstantsGenerator] 未找到任何有效的 Addressables 分组");
                    return;
                }

                // 生成代码
                var code = GenerateCode(groups, config);

                // 写入文件
                WriteToFile(config.constantsOutputPath, config.constantsClassName, code);

                Debug.Log($"[AddressableConstantsGenerator] 资源常量生成完成，共 {groups.Sum(g => g.Entries.Count)} 个条目");
            }
            catch (Exception ex)
            {
                Debug.LogError($"[AddressableConstantsGenerator] 生成失败: {ex.Message}\n{ex.StackTrace}");
            }
        }

        /// <summary>
        ///     获取生成的文件路径
        /// </summary>
        public static string GetOutputFilePath(AddressableConfig config)
        {
            return Path.Combine(config.constantsOutputPath, $"{config.constantsClassName}.cs");
        }

        #endregion

        #region 数据收集

        /// <summary>
        ///     收集所有分组数据
        /// </summary>
        private static List<GroupData> CollectGroups(
            AddressableAssetSettings settings,
            AddressableConfig config)
        {
            var result = new List<GroupData>();
            var excludedSet = new HashSet<string>(config.excludedGroups ?? new List<string>(),
                StringComparer.OrdinalIgnoreCase);

            foreach (var group in settings.groups)
            {
                if (group == null)
                    continue;

                // 跳过排除的分组
                if (excludedSet.Contains(group.Name))
                    continue;

                // 跳过空分组
                if (group.entries == null || group.entries.Count == 0)
                    continue;

                var groupData = CollectGroupData(group, config);
                if (groupData.Entries.Count > 0) result.Add(groupData);
            }

            // 按分组名排序
            result.Sort((a, b) => string.Compare(a.ClassName, b.ClassName, StringComparison.Ordinal));

            return result;
        }

        /// <summary>
        ///     收集单个分组数据
        /// </summary>
        private static GroupData CollectGroupData(
            AddressableAssetGroup group,
            AddressableConfig config)
        {
            var groupData = new GroupData
            {
                GroupName = group.Name,
                ClassName = ConvertToClassName(group.Name, config.namingConvention),
                Entries = new List<EntryData>()
            };

            // 用于检测同分组内重复地址
            var addressCountMap = new Dictionary<string, int>();

            foreach (var entry in group.entries)
            {
                if (entry == null || string.IsNullOrEmpty(entry.address))
                    continue;

                var address = entry.address;

                // 计算常量名
                var baseConstantName = ConvertToConstantName(address, config.namingConvention);

                // 处理重复地址
                var constantName = baseConstantName;
                if (addressCountMap.TryGetValue(address, out var count))
                {
                    count++;
                    constantName = $"{baseConstantName}_{count}";
                    addressCountMap[address] = count;
                }
                else
                {
                    addressCountMap[address] = 1;
                }

                groupData.Entries.Add(new EntryData
                {
                    Address = address,
                    ConstantName = constantName,
                    Labels = entry.labels?.ToList() ?? new List<string>()
                });
            }

            // 按常量名排序
            groupData.Entries.Sort((a, b) => string.Compare(a.ConstantName, b.ConstantName, StringComparison.Ordinal));

            return groupData;
        }

        #endregion

        #region 代码生成

        /// <summary>
        ///     生成代码内容
        /// </summary>
        private static string GenerateCode(List<GroupData> groups, AddressableConfig config)
        {
            var sb = new StringBuilder();
            var indent = new string(' ', 4);

            // 文件头
            sb.AppendLine(AutoGeneratedHeader);
            sb.AppendLine();

            // 命名空间
            if (!string.IsNullOrEmpty(config.constantsNamespace))
            {
                sb.AppendLine($"namespace {config.constantsNamespace}");
                sb.AppendLine("{");
            }

            // 类定义
            var classIndent = string.IsNullOrEmpty(config.constantsNamespace) ? "" : indent;
            sb.AppendLine($"{classIndent}/// <summary>");
            sb.AppendLine($"{classIndent}/// Addressables 资源常量，按 Group 分组");
            sb.AppendLine($"{classIndent}/// </summary>");
            sb.AppendLine($"{classIndent}public static partial class {config.constantsClassName}");
            sb.AppendLine($"{classIndent}{{");

            // 生成各分组类
            var groupIndent = classIndent + indent;
            for (var i = 0; i < groups.Count; i++)
            {
                GenerateGroupClass(sb, groups[i], groupIndent, config);

                if (i < groups.Count - 1) sb.AppendLine();
            }

            // 类结束
            sb.AppendLine($"{classIndent}}}");

            // 命名空间结束
            if (!string.IsNullOrEmpty(config.constantsNamespace)) sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        ///     生成分组类
        /// </summary>
        private static void GenerateGroupClass(
            StringBuilder sb,
            GroupData group,
            string indent,
            AddressableConfig config)
        {
            // 检查是否需要嵌套分组（根据地址路径）
            var nestedGroups = BuildNestedGroups(group, config);

            // 分组注释
            sb.AppendLine($"{indent}/// <summary>");
            sb.AppendLine($"{indent}/// Group: {group.GroupName}");
            sb.AppendLine($"{indent}/// </summary>");
            sb.AppendLine($"{indent}public static class {group.ClassName}");
            sb.AppendLine($"{indent}{{");

            var entryIndent = indent + "    ";

            if (nestedGroups != null && nestedGroups.Count > 0)
            {
                // 嵌套分组
                var idx = 0;
                foreach (var nested in nestedGroups)
                {
                    if (nested.Entries.Count == 0)
                        continue;

                    sb.AppendLine();
                    sb.AppendLine($"{entryIndent}/// <summary>");
                    sb.AppendLine($"{entryIndent}/// {nested.ClassName}");
                    sb.AppendLine($"{entryIndent}/// </summary>");
                    sb.AppendLine($"{entryIndent}public static class {nested.ClassName}");
                    sb.AppendLine($"{entryIndent}{{");

                    var nestedEntryIndent = entryIndent + "    ";
                    foreach (var entry in nested.Entries) GenerateEntry(sb, entry, nestedEntryIndent);

                    sb.AppendLine($"{entryIndent}}}");

                    if (idx < nestedGroups.Count - 1) sb.AppendLine();
                    idx++;
                }
            }
            else
            {
                // 扁平结构
                foreach (var entry in group.Entries) GenerateEntry(sb, entry, entryIndent);
            }

            sb.AppendLine($"{indent}}}");
        }

        /// <summary>
        ///     构建嵌套分组（按地址路径的第一级目录）
        /// </summary>
        private static List<NestedGroupData> BuildNestedGroups(GroupData group, AddressableConfig config)
        {
            if (!config.enableNestedGroups)
                return null;

            var result = new List<NestedGroupData>();
            var nestedMap = new Dictionary<string, List<EntryData>>();

            foreach (var entry in group.Entries)
            {
                var firstSegment = GetFirstPathSegment(entry.Address);
                if (string.IsNullOrEmpty(firstSegment)) firstSegment = "_Root";

                if (!nestedMap.TryGetValue(firstSegment, out var list))
                {
                    list = new List<EntryData>();
                    nestedMap[firstSegment] = list;
                }

                list.Add(entry);
            }

            foreach (var kvp in nestedMap)
                result.Add(new NestedGroupData
                {
                    ClassName = ConvertToClassName(kvp.Key, config.namingConvention),
                    Entries = kvp.Value
                });

            result.Sort((a, b) => string.Compare(a.ClassName, b.ClassName, StringComparison.Ordinal));
            return result;
        }

        /// <summary>
        ///     获取地址路径的第一个片段
        /// </summary>
        private static string GetFirstPathSegment(string address)
        {
            if (string.IsNullOrEmpty(address))
                return null;

            var slashIndex = address.IndexOf('/');
            if (slashIndex > 0) return address.Substring(0, slashIndex);

            return null;
        }

        /// <summary>
        ///     生成单个条目
        /// </summary>
        private static void GenerateEntry(StringBuilder sb, EntryData entry, string indent)
        {
            // 注释（包含标签信息）
            if (entry.Labels.Count > 0)
            {
                sb.AppendLine($"{indent}/// <summary>");
                sb.AppendLine($"{indent}/// Labels: {string.Join(", ", entry.Labels)}");
                sb.AppendLine($"{indent}/// </summary>");
            }

            sb.AppendLine($"{indent}public const string {entry.ConstantName} = \"{EscapeString(entry.Address)}\";");
        }

        #endregion

        #region 命名转换

        /// <summary>
        ///     将字符串转换为合法的类名
        /// </summary>
        private static string ConvertToClassName(string name, NamingConvention convention)
        {
            if (string.IsNullOrEmpty(name))
                return "_";

            // 移除非法字符，保留字母、数字、下划线和空格
            var cleaned = CleanName(name);

            // 应用命名规则
            return ApplyNamingConvention(cleaned, convention);
        }

        /// <summary>
        ///     将地址转换为常量名
        /// </summary>
        private static string ConvertToConstantName(string address, NamingConvention convention)
        {
            if (string.IsNullOrEmpty(address))
                return "_";

            // 提取文件名或最后一段
            var name = ExtractNameFromAddress(address);

            // 清理并转换
            var cleaned = CleanName(name);

            // 应用命名规则（常量通常用 PascalCase）
            var result = ApplyNamingConvention(cleaned, NamingConvention.PascalCase);

            // 确保不以数字开头
            if (result.Length > 0 && char.IsDigit(result[0])) result = "_" + result;

            return result;
        }

        /// <summary>
        ///     从地址中提取名称（取最后一段）
        /// </summary>
        private static string ExtractNameFromAddress(string address)
        {
            if (string.IsNullOrEmpty(address))
                return "_";

            // 移除文件扩展名
            var name = Path.GetFileNameWithoutExtension(address);

            // 如果为空，使用最后一段路径
            if (string.IsNullOrEmpty(name))
            {
                var lastSlash = address.LastIndexOf('/');
                name = lastSlash >= 0 ? address.Substring(lastSlash + 1) : address;
            }

            return name;
        }

        /// <summary>
        ///     清理名称中的非法字符
        /// </summary>
        private static string CleanName(string name)
        {
            if (string.IsNullOrEmpty(name))
                return "_";

            var sb = new StringBuilder();
            var prevIsSeparator = false;

            foreach (var c in name)
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(c);
                    prevIsSeparator = false;
                }
                else if (c == '_' || c == ' ' || c == '-' || c == '/' || c == '\\' || c == '.')
                {
                    // 分隔符统一转为单词边界
                    if (!prevIsSeparator && sb.Length > 0)
                    {
                        sb.Append(' ');
                        prevIsSeparator = true;
                    }
                }

            // 其他字符忽略
            var result = sb.ToString().Trim();
            return string.IsNullOrEmpty(result) ? "_" : result;
        }

        /// <summary>
        ///     应用命名规则
        /// </summary>
        private static string ApplyNamingConvention(string name, NamingConvention convention)
        {
            if (string.IsNullOrEmpty(name))
                return "_";

            // 按空格分割单词
            var words = name.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);

            return convention switch
            {
                NamingConvention.PascalCase => string.Concat(words.Select(w =>
                    char.ToUpper(w[0]) + (w.Length > 1 ? w.Substring(1).ToLower() : ""))),

                NamingConvention.CamelCase => words.Length == 1
                    ? words[0].ToLower()
                    : char.ToLower(words[0][0]) + (words[0].Length > 1 ? words[0].Substring(1).ToLower() : "") +
                      string.Concat(words.Skip(1).Select(w =>
                          char.ToUpper(w[0]) + (w.Length > 1 ? w.Substring(1).ToLower() : ""))),

                NamingConvention.LowerCase => string.Concat(words.Select(w => w.ToLower())),

                NamingConvention.Original => string.Join("", words),

                _ => string.Concat(words.Select(w =>
                    char.ToUpper(w[0]) + (w.Length > 1 ? w.Substring(1).ToLower() : "")))
            };
        }

        #endregion

        #region 工具方法

        /// <summary>
        ///     转义字符串中的特殊字符
        /// </summary>
        private static string EscapeString(string value)
        {
            return value?.Replace("\\", "\\\\")
                       .Replace("\"", "\\\"")
                       .Replace("\n", "\\n")
                       .Replace("\r", "\\r")
                       .Replace("\t", "\\t")
                   ?? "";
        }

        /// <summary>
        ///     写入文件
        ///     仅在内容发生变化时才写入并刷新，避免不必要的域重载
        /// </summary>
        private static void WriteToFile(string directory, string className, string code)
        {
            // 确保目录存在
            if (!Directory.Exists(directory)) Directory.CreateDirectory(directory);

            var filePath = Path.Combine(directory, $"{className}.cs");

            // 比较现有内容，无变化则跳过写入
            if (File.Exists(filePath))
            {
                var existing = File.ReadAllText(filePath, Encoding.UTF8);
                if (existing == code)
                {
                    Debug.Log("[AddressableConstantsGenerator] 常量文件无变化，跳过写入");
                    return;
                }
            }

            File.WriteAllText(filePath, code, Encoding.UTF8);

            // 刷新资源数据库
            AssetDatabase.Refresh();
        }

        #endregion

        #region 内部类

        /// <summary>
        ///     分组数据
        /// </summary>
        private sealed class GroupData
        {
            public string ClassName;
            public List<EntryData> Entries;
            public string GroupName;
        }

        /// <summary>
        ///     条目数据
        /// </summary>
        private sealed class EntryData
        {
            public string Address;
            public string ConstantName;
            public List<string> Labels;
        }

        /// <summary>
        ///     嵌套分组数据
        /// </summary>
        private sealed class NestedGroupData
        {
            public string ClassName;
            public List<EntryData> Entries;
        }

        #endregion
    }
}