#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.Audio;

namespace CFramework.Editor
{
    /// <summary>
    ///     AudioGroup 枚举自动生成工具
    ///     <para>读取 AudioMixer 中的所有 Group 路径，自动计算 Animator.StringToHash 并生成 C# 枚举</para>
    ///     <para>生成结果固定为 CFramework.AudioGroup 枚举，与框架音频系统绑定</para>
    ///     <para>使用：菜单 CFramework > Generate > AudioGroup Enum</para>
    /// </summary>
    public class AudioGroupGeneratorWindow : EditorWindow
    {
        // 固定枚举元数据，框架契约不可更改
        private const string FixedNamespace = "CFramework";
        private const string FixedEnumName = "AudioGroup";
        private const string FixedFileHeader = "/// <auto-generated />\n" +
                                               "/// 本文件由 AudioGroupGenerator 自动生成，请勿手动修改\n" +
                                               "/// {0}\n" +
                                               "/// AudioMixer：{1}\n";

        private AudioMixer _mixer;
        private string _outputPath = "Assets/AudioGroup.cs";
        private Vector2 _scroll;
        private List<GroupInfo> _previewGroups = new();
        private bool _previewDirty = true;

        private struct GroupInfo
        {
            public string Path;
            public int Hash;
            public string MemberName;
        }

        [MenuItem("CFramework/Generate/AudioGroup Enum", priority = 100)]
        public static void ShowWindow()
        {
            var window = GetWindow<AudioGroupGeneratorWindow>("AudioGroup 生成器");
            window.minSize = new Vector2(400, 280);
            window.Show();
        }

        private void OnEnable()
        {
            var lastMixer = EditorPrefs.GetString("CFramework_AudioGroup_Mixer", "");
            if (!string.IsNullOrEmpty(lastMixer))
                _mixer = AssetDatabase.LoadAssetAtPath<AudioMixer>(lastMixer);

            _outputPath = EditorPrefs.GetString("CFramework_AudioGroup_Output", _outputPath);
        }

        private void OnGUI()
        {
            EditorGUILayout.Space(8);
            EditorGUILayout.LabelField("AudioGroup 枚举自动生成", EditorStyles.boldLabel);

            EditorGUILayout.HelpBox(
                "读取 AudioMixer 中的所有 Group 路径，自动计算 Animator.StringToHash 并生成 C# 枚举。\n\n" +
                "生成结果固定为 CFramework.AudioGroup，与框架音频系统强绑定。\n" +
                "每次修改 Mixer 路径后需重新生成。",
                MessageType.Info);

            EditorGUILayout.Space(4);
            EditorGUILayout.LabelField("配置", EditorStyles.boldLabel);

            // 选择 AudioMixer
            EditorGUI.BeginChangeCheck();
            _mixer = (AudioMixer)EditorGUILayout.ObjectField("AudioMixer", _mixer, typeof(AudioMixer), false);
            if (EditorGUI.EndChangeCheck())
            {
                _previewDirty = true;
                if (_mixer != null)
                    EditorPrefs.SetString("CFramework_AudioGroup_Mixer", AssetDatabase.GetAssetPath(_mixer));
            }

            // 输出路径（唯一可配置项）
            EditorGUILayout.BeginHorizontal();
            EditorGUI.BeginChangeCheck();
            _outputPath = EditorGUILayout.TextField("输出路径", _outputPath);
            if (EditorGUILayout.Button("浏览...", GUILayout.Width(60)))
            {
                var selected = EditorUtility.SaveFilePanelInProject(
                    "选择输出路径",
                    "AudioGroup.cs",
                    "cs",
                    "选择 AudioGroup.cs 的输出路径");
                if (!string.IsNullOrEmpty(selected))
                {
                    _outputPath = selected;
                    _previewDirty = true;
                }
            }
            EditorGUILayout.EndHorizontal();
            if (EditorGUI.EndChangeCheck())
                EditorPrefs.SetString("CFramework_AudioGroup_Output", _outputPath);

            // 显示固定信息
            EditorGUI.BeginDisabledGroup(true);
            EditorGUILayout.TextField("命名空间", FixedNamespace);
            EditorGUILayout.TextField("枚举名", FixedEnumName);
            EditorGUI.EndDisabledGroup();

            EditorGUILayout.Space(8);
            EditorGUILayout.LabelField("预览", EditorStyles.boldLabel);

            if (_mixer != null)
            {
                if (_previewDirty)
                {
                    _previewGroups = CollectGroups(_mixer);
                    _previewDirty = false;
                }

                using (var scroll = new EditorGUILayout.ScrollViewScope(_scroll, GUILayout.Height(140)))
                {
                    _scroll = scroll.scrollPosition;
                    foreach (var g in _previewGroups)
                    {
                        EditorGUILayout.LabelField($"  {g.Path}", $"= {g.Hash}");
                    }
                }

                EditorGUILayout.HelpBox($"共 {_previewGroups.Count} 个 Group", MessageType.None);
            }
            else
            {
                EditorGUILayout.HelpBox("请先指定 AudioMixer", MessageType.Warning);
            }

            EditorGUILayout.Space(8);

            // 生成按钮
            GUI.enabled = _mixer != null && !string.IsNullOrWhiteSpace(_outputPath);
            if (GUILayout.Button("生成 AudioGroup.cs", GUILayout.Height(30)))
            {
                Generate(_mixer, _outputPath);
            }
            GUI.enabled = true;

            EditorGUILayout.Space(4);
            if (GUILayout.Button("在文件夹中打开", GUILayout.Height(22)))
            {
                if (File.Exists(_outputPath))
                    EditorUtility.RevealInFinder(_outputPath);
            }
        }

        /// <summary>
        ///     从 AudioMixer 收集所有 Group 路径
        /// </summary>
        private static List<GroupInfo> CollectGroups(AudioMixer mixer)
        {
            var groups = new List<GroupInfo>();
            var mixerObj = new SerializedObject(mixer);
            var childPlugins = mixerObj.FindProperty("m_ChildPlugins");

            if (childPlugins != null && childPlugins.isArray)
            {
                for (int i = 0; i < childPlugins.arraySize; i++)
                    CollectChildGroups(childPlugins.GetArrayElementAtIndex(i), "", groups);
            }

            return groups;
        }

        private static void CollectChildGroups(SerializedProperty prop, string parentPath, List<GroupInfo> groups)
        {
            var nameProp = prop.FindPropertyRelative("Name");
            var name = nameProp?.stringValue ?? "";
            if (string.IsNullOrEmpty(name)) return;

            var fullPath = string.IsNullOrEmpty(parentPath) ? name : $"{parentPath}/{name}";
            groups.Add(new GroupInfo
            {
                Path = fullPath,
                Hash = Animator.StringToHash(fullPath),
                MemberName = fullPath.Replace("/", "_")
            });

            var childrenProp = prop.FindPropertyRelative("Children");
            if (childrenProp != null && childrenProp.isArray)
            {
                for (int i = 0; i < childrenProp.arraySize; i++)
                    CollectChildGroups(childrenProp.GetArrayElementAtIndex(i), fullPath, groups);
            }
        }

        /// <summary>
        ///     生成 AudioGroup.cs 枚举文件
        /// </summary>
        public static void Generate(AudioMixer mixer, string outputPath)
        {
            var groups = CollectGroups(mixer);

            if (groups.Count == 0)
            {
                EditorUtility.DisplayDialog("AudioGroup 生成器", "未在 AudioMixer 中找到任何 Group", "确定");
                return;
            }

            var sb = new StringBuilder();
            var timestamp = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
            var mixerPath = AssetDatabase.GetAssetPath(mixer);
            sb.AppendFormat(FixedFileHeader, $"生成时间：{timestamp}", mixerPath);
            sb.AppendLine();
            sb.AppendLine("#if CFRAMEWORK_AUDIO");
            sb.AppendLine("using System.ComponentModel;");
            sb.AppendLine();
            sb.AppendLine($"namespace {FixedNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    ///     音频分组枚举");
            sb.AppendLine("    ///     <para>值 = Animator.StringToHash(Group路径)，用于运行时 O(1) 查找</para>");
            sb.AppendLine("    ///     <para>对应 AudioMixer 的 Group 层级</para>");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public enum {FixedEnumName}");
            sb.AppendLine("    {");

            for (int i = 0; i < groups.Count; i++)
            {
                var g = groups[i];
                sb.AppendLine($"        [Description(\"{g.Path}\")]");
                sb.AppendLine($"        {g.MemberName} = {g.Hash}{(i < groups.Count - 1 ? "," : "")}");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#endif");

            // 确保目录存在
            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();

            EditorUtility.DisplayDialog(
                "生成成功",
                $"已生成 {groups.Count} 个枚举成员：\n{outputPath}",
                "确定");

            EditorGUIUtility.PingObject(AssetDatabase.LoadAssetAtPath<TextAsset>(outputPath));
        }
    }
}
#endif
