#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using CFramework.Editor.Utilities;
using UnityEditor;
using UnityEngine;
using UnityEngine.Audio;
using UnityEngine.UIElements;

namespace CFramework.Editor
{
    /// <summary>
    ///     AudioGroup 枚举自动生成工具（UIToolkit 实现）
    /// </summary>
    public class AudioGroupGeneratorWindow : EditorWindow
    {
        private const string USS_FILE_NAME = "AudioGroupGenerator.uss";
        private const string FixedNamespace = "CFramework";
        private const string FixedEnumName = "AudioGroup";
        private const string FixedFileHeader = "/// <auto-generated />\n" +
                                               "/// 本文件由 AudioGroupGenerator 自动生成，请勿手动修改\n" +
                                               "/// {0}\n" +
                                               "/// AudioMixer：{1}\n";

        [MenuItem("CFramework/生成/AudioGroup 枚举", priority = 100)]
        public static void ShowWindow()
        {
            var window = GetWindow<AudioGroupGeneratorWindow>("AudioGroup 生成器");
            window.minSize = new Vector2(450, 520);
            window.Show();
        }

        #region 字段

        private VisualElement _mixerSelectorRow;
        private Label _mixerNameLabel;
        private TextField _outputPathField;
        private Button _browseButton;
        private Toggle _autoDefineToggle;
        private Button _registerMacroBtn;
        private Button _unregisterMacroBtn;
        private ScrollView _previewScroll;
        private Label _previewCountLabel;
        private Button _generateButton;
        private Button _openFolderButton;
        private Label _warningLabel;

        private AudioMixer _mixer;
        private string _outputPath = "Assets/AudioGroup.cs";
        private bool _autoDefineSymbol = true;
        private List<GroupInfo> _previewGroups = new List<GroupInfo>();
        private bool _previewDirty = true;

        #endregion

        #region 结构体

        private struct GroupInfo
        {
            public string Path;
            public int Hash;
            public string MemberName;
        }

        #endregion

        private void CreateGUI()
        {
            var root = rootVisualElement;

            // 加载 USS 样式表
            var styleSheet = EditorStyleSheet.Find(USS_FILE_NAME);
            if (styleSheet != null) root.styleSheets.Add(styleSheet);

            // 标题
            var titleLabel = new Label("AudioGroup 枚举自动生成");
            titleLabel.AddToClassList("window-title");
            root.Add(titleLabel);

            // 提示信息框
            var helpBox = new HelpBox(
                "读取 AudioMixer 中的所有 Group 路径，自动计算 Animator.StringToHash 并生成 C# 枚举。\n\n" +
                "生成的 AudioGroup 枚举附带扩展方法 ToPath()，可直接传给音频系统接口。\n" +
                "每次修改 Mixer 路径后需重新生成。",
                HelpBoxMessageType.Info);
            helpBox.AddToClassList("help-box");
            root.Add(helpBox);

            // ===== 配置区域 =====
            var configLabel = new Label("配置");
            configLabel.AddToClassList("config-section-label");
            root.Add(configLabel);

            // AudioMixer 选择
            var mixerRow = new VisualElement();
            mixerRow.AddToClassList("row");

            var mixerLabel = new Label("AudioMixer");
            mixerLabel.AddToClassList("field-label");
            mixerRow.Add(mixerLabel);

            _mixerSelectorRow = new VisualElement();
            _mixerSelectorRow.style.flexDirection = FlexDirection.Row;
            _mixerSelectorRow.style.flexGrow = 1;
            _mixerSelectorRow.style.alignItems = Align.Center;

            _mixerNameLabel = new Label(_mixer != null ? _mixer.name : "None (AudioMixer)");
            _mixerNameLabel.AddToClassList("mixer-name");
            _mixerNameLabel.AddToClassList(_mixer != null ? "has-value" : "no-value");
            _mixerSelectorRow.Add(_mixerNameLabel);

            var selectMixerBtn = new Button(OnSelectMixerClicked);
            selectMixerBtn.text = "Select";
            selectMixerBtn.AddToClassList("select-btn");
            _mixerSelectorRow.Add(selectMixerBtn);

            var clearMixerBtn = new Button(() => { _mixer = null; UpdateMixerDisplay(); });
            clearMixerBtn.text = "X";
            clearMixerBtn.AddToClassList("clear-btn");
            _mixerSelectorRow.Add(clearMixerBtn);

            mixerRow.Add(_mixerSelectorRow);
            root.Add(mixerRow);

            // 输出路径
            var pathRow = new VisualElement();
            pathRow.AddToClassList("row");

            var pathLabel = new Label("输出路径");
            pathLabel.AddToClassList("field-label");
            pathRow.Add(pathLabel);

            var pathContainer = new VisualElement();
            pathContainer.style.flexDirection = FlexDirection.Row;
            pathContainer.style.flexGrow = 1;
            pathContainer.style.alignItems = Align.Center;

            _outputPathField = new TextField("");
            _outputPathField.style.flexGrow = 1;
            _outputPathField.style.marginRight = 4;
            _outputPathField.RegisterValueChangedCallback(evt =>
            {
                _outputPath = evt.newValue;
                EditorPrefs.SetString("CFramework_AudioGroup_Output", _outputPath);
            });
            pathContainer.Add(_outputPathField);

            _browseButton = new Button(OnBrowseClicked);
            _browseButton.text = "浏览...";
            _browseButton.AddToClassList("browse-btn");
            pathContainer.Add(_browseButton);

            pathRow.Add(pathContainer);
            root.Add(pathRow);

            // 固定信息（只读）
            var nsField = new TextField(FixedNamespace);
            nsField.isReadOnly = true;
            nsField.label = "命名空间";
            nsField.style.marginBottom = 4;
            root.Add(nsField);

            var enumField = new TextField(FixedEnumName);
            enumField.isReadOnly = true;
            enumField.label = "枚举名";
            enumField.style.marginBottom = 4;
            root.Add(enumField);

            // 宏定义开关
            _autoDefineToggle = new Toggle("自动注册 CFRAMEWORK_AUDIO 宏");
            _autoDefineToggle.tooltip = "生成枚举的同时，在项目的 Scripting Define Symbols 中注册 CFRAMEWORK_AUDIO 宏定义。";
            _autoDefineToggle.value = _autoDefineSymbol;
            _autoDefineToggle.style.marginTop = 4;
            _autoDefineToggle.style.marginBottom = 4;
            _autoDefineToggle.RegisterValueChangedCallback(evt =>
            {
                _autoDefineSymbol = evt.newValue;
                EditorPrefs.SetBool("CFramework_AudioGroup_AutoDefine", _autoDefineSymbol);
            });
            root.Add(_autoDefineToggle);

            // 宏操作按钮行
            var macroRow = new VisualElement();
            macroRow.AddToClassList("macro-row");

            _registerMacroBtn = new Button(() =>
            {
                DefineSymbol("CFRAMEWORK_AUDIO");
                EditorUtility.DisplayDialog("宏定义", "CFRAMEWORK_AUDIO 宏定义已注册", "确定");
            });
            _registerMacroBtn.text = "注册宏定义";
            _registerMacroBtn.style.marginRight = 6;
            macroRow.Add(_registerMacroBtn);

            _unregisterMacroBtn = new Button(() =>
            {
                UndefineSymbol("CFRAMEWORK_AUDIO");
                EditorUtility.DisplayDialog("宏定义", "CFRAMEWORK_AUDIO 宏定义已取消注册", "确定");
            });
            _unregisterMacroBtn.text = "取消注册宏定义";
            _unregisterMacroBtn.style.marginRight = 6;
            macroRow.Add(_unregisterMacroBtn);

            macroRow.Add(new VisualElement { style = { flexGrow = 1 } });
            root.Add(macroRow);

            // ===== 预览区域 =====
            var previewLabel = new Label("预览");
            previewLabel.AddToClassList("config-section-label");
            root.Add(previewLabel);

            var previewContainer = new VisualElement();
            previewContainer.AddToClassList("preview-container");

            _warningLabel = new Label("请先指定 AudioMixer");
            _warningLabel.AddToClassList("warning-label");
            previewContainer.Add(_warningLabel);

            _previewScroll = new ScrollView();
            _previewScroll.style.maxHeight = 130;
            _previewScroll.style.display = DisplayStyle.None;
            previewContainer.Add(_previewScroll);

            _previewCountLabel = new Label("");
            _previewCountLabel.AddToClassList("preview-count");
            _previewCountLabel.style.display = DisplayStyle.None;
            previewContainer.Add(_previewCountLabel);

            root.Add(previewContainer);

            // ===== 操作按钮 =====
            _generateButton = new Button(OnGenerateClicked);
            _generateButton.text = "生成 AudioGroup.cs";
            _generateButton.AddToClassList("generate-button");
            root.Add(_generateButton);

            _openFolderButton = new Button(OnOpenFolderClicked);
            _openFolderButton.text = "在文件夹中打开";
            _openFolderButton.AddToClassList("open-folder-button");
            root.Add(_openFolderButton);
        }

        private void OnEnable()
        {
            var lastMixer = EditorPrefs.GetString("CFramework_AudioGroup_Mixer", "");
            if (!string.IsNullOrEmpty(lastMixer))
                _mixer = AssetDatabase.LoadAssetAtPath<AudioMixer>(lastMixer);

            _outputPath = EditorPrefs.GetString("CFramework_AudioGroup_Output", _outputPath);
            _autoDefineSymbol = EditorPrefs.GetBool("CFramework_AudioGroup_AutoDefine", true);

            EditorApplication.delayCall += () =>
            {
                UpdateMixerDisplay();
                if (_outputPathField != null) _outputPathField.value = _outputPath;
                if (_autoDefineToggle != null) _autoDefineToggle.value = _autoDefineSymbol;
                RefreshPreview();
                UpdateGenerateButtonState();
            };
        }

        private void OnSelectMixerClicked()
        {
            var path = EditorUtility.OpenFilePanel("Select AudioMixer", "Assets/", "mixer");
            if (!string.IsNullOrEmpty(path) && path.StartsWith(Application.dataPath))
            {
                var assetPath = "Assets" + path.Substring(Application.dataPath.Length);
                _mixer = AssetDatabase.LoadAssetAtPath<AudioMixer>(assetPath);
                if (_mixer != null)
                {
                    EditorPrefs.SetString("CFramework_AudioGroup_Mixer", assetPath);
                    _previewDirty = true;
                    UpdateMixerDisplay();
                    RefreshPreview();
                }
                else
                {
                    EditorUtility.DisplayDialog("选择失败", "请选择有效的 AudioMixer 资产", "确定");
                }
            }
        }

        private void UpdateMixerDisplay()
        {
            if (_mixerNameLabel != null)
            {
                _mixerNameLabel.text = _mixer != null ? $"{_mixer.name} (AudioMixer)" : "None (AudioMixer)";
                _mixerNameLabel.RemoveFromClassList("has-value");
                _mixerNameLabel.RemoveFromClassList("no-value");
                _mixerNameLabel.AddToClassList(_mixer != null ? "has-value" : "no-value");
            }
        }

        private void OnBrowseClicked()
        {
            var selected = EditorUtility.SaveFilePanelInProject(
                "选择输出路径",
                "AudioGroup.cs",
                "cs",
                "选择 AudioGroup.cs 的输出路径");

            if (!string.IsNullOrEmpty(selected))
            {
                _outputPath = selected;
                _outputPathField.value = selected;
                _previewDirty = true;
            }
        }

        private void OnGenerateClicked() => Generate(_mixer, _outputPath, _autoDefineSymbol);

        private void OnOpenFolderClicked()
        {
            if (File.Exists(_outputPath))
                EditorUtility.RevealInFinder(_outputPath);
        }

        private void RefreshPreview()
        {
            bool hasMixer = _mixer != null;

            _warningLabel.style.display = hasMixer ? DisplayStyle.None : DisplayStyle.Flex;
            _previewScroll.style.display = hasMixer ? DisplayStyle.Flex : DisplayStyle.None;
            _previewCountLabel.style.display = hasMixer ? DisplayStyle.Flex : DisplayStyle.None;

            if (!hasMixer) return;

            if (_previewDirty)
            {
                _previewGroups = CollectGroups(_mixer);
                _previewDirty = false;
            }

            _previewScroll.Clear();
            foreach (var g in _previewGroups)
            {
                var item = new Label($"  {g.Path}  =  {g.Hash}");
                item.AddToClassList("preview-item");
                _previewScroll.Add(item);
            }

            _previewCountLabel.text = $"共 {_previewGroups.Count} 个 Group";
        }

        private void UpdateGenerateButtonState()
        {
            if (_generateButton != null)
                _generateButton.SetEnabled(_mixer != null && !string.IsNullOrWhiteSpace(_outputPath));
        }

        #region 业务逻辑

        private static List<GroupInfo> CollectGroups(AudioMixer mixer)
        {
            var mixerSerialized = new SerializedObject(mixer);
            var masterProp = mixerSerialized.FindProperty("m_MasterGroup");
            var groups = new List<GroupInfo>();
            CollectChildGroups(masterProp, "", groups);
            return groups;
        }

        private static void CollectChildGroups(SerializedProperty groupProp, string parentPath, List<GroupInfo> groups)
        {
            if (groupProp == null || groupProp.objectReferenceValue == null) return;

            var groupSerialized = new SerializedObject(groupProp.objectReferenceValue);
            var nameProp = groupSerialized.FindProperty("m_Name");
            var name = nameProp?.stringValue ?? "";
            if (string.IsNullOrEmpty(name)) return;

            var fullPath = string.IsNullOrEmpty(parentPath) ? name : $"{parentPath}/{name}";
            groups.Add(new GroupInfo { Path = fullPath, Hash = Animator.StringToHash(fullPath), MemberName = name });

            var childrenProp = groupSerialized.FindProperty("m_Children");
            if (childrenProp != null && childrenProp.isArray)
            {
                for (int i = 0; i < childrenProp.arraySize; i++)
                    CollectChildGroups(childrenProp.GetArrayElementAtIndex(i), fullPath, groups);
            }
        }

        private static void DefineSymbol(string symbol)
        {
            var buildTarget = EditorUserBuildSettings.activeBuildTarget;
            var group = BuildPipeline.GetBuildTargetGroup(buildTarget);
            var defines = PlayerSettings.GetScriptingDefineSymbolsForGroup(group);
            if (defines.Contains(symbol)) return;
            PlayerSettings.SetScriptingDefineSymbolsForGroup(group, $"{defines};{symbol}");
        }

        private static void UndefineSymbol(string symbol)
        {
            var buildTarget = EditorUserBuildSettings.activeBuildTarget;
            var group = BuildPipeline.GetBuildTargetGroup(buildTarget);
            var defines = PlayerSettings.GetScriptingDefineSymbolsForGroup(group);
            if (!defines.Contains(symbol)) return;
            var parts = defines.Split(';');
            var newDefines = new List<string>();
            foreach (var part in parts) { if (part.Trim() != symbol) newDefines.Add(part.Trim()); }
            PlayerSettings.SetScriptingDefineSymbolsForGroup(group, string.Join(";", newDefines));
        }

        public static void Generate(AudioMixer mixer, string outputPath, bool autoDefineSymbol)
        {
            var groups = CollectGroups(mixer);
            if (groups.Count == 0)
            {
                EditorUtility.DisplayDialog("AudioGroup 生成器", "未在 AudioMixer 中找到任何 Group", "确定");
                return;
            }

            var sb = new StringBuilder();
            var timestamp = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
            var mixerPath = AssetDatabase.GetAssetPath(mixer);
            sb.AppendFormat(FixedFileHeader, $"生成时间：{timestamp}", mixerPath);
            sb.AppendLine();
            sb.AppendLine("#if CFRAMEWORK_AUDIO");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.ComponentModel;");
            sb.AppendLine();
            sb.AppendLine($"namespace {FixedNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public enum {FixedEnumName}");
            sb.AppendLine("    {");
            for (int i = 0; i < groups.Count; i++)
            {
                var g = groups[i];
                sb.AppendLine($"        [Description(\"{g.Path}\")]");
                sb.AppendLine($"        {g.MemberName} = {g.Hash}{(i < groups.Count - 1 ? "," : "")}");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    internal static class AudioGroupPaths");
            sb.AppendLine("    {");
            sb.AppendLine("        private static readonly Dictionary<int, string> _map = new();");
            sb.AppendLine("        private static bool _initialized;");
            sb.AppendLine("        internal static string GetPath(int hash)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (!_initialized)");
            sb.AppendLine("            {");
            sb.AppendLine("                _initialized = true;");
            foreach (var g in groups) sb.AppendLine($"                _map[{g.Hash}] = \"{g.Path}\";");
            sb.AppendLine("            }");
            sb.AppendLine("            return _map.TryGetValue(hash, out var path) ? path : null;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static class AudioGroupExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        public static string ToPath(this AudioGroup group) => AudioGroupPaths.GetPath((int)group);");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#endif");

            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir)) Directory.CreateDirectory(dir);
            File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();

            if (autoDefineSymbol) DefineSymbol("CFRAMEWORK_AUDIO");

            EditorUtility.DisplayDialog(
                "生成成功",
                $"已生成 {groups.Count} 个枚举成员：\n{outputPath}" + (autoDefineSymbol ? "\n\n已注册 CFRAMEWORK_AUDIO 宏定义。" : ""),
                "确定");

            EditorGUIUtility.PingObject(AssetDatabase.LoadAssetAtPath<TextAsset>(outputPath));
        }

        #endregion
    }
}
#endif
