#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.Audio;

namespace CFramework.Editor
{
    /// <summary>
    ///     AudioGroup 枚举自动生成工具
    ///     <para>读取 AudioMixer 中的所有 Group 路径，自动计算 Animator.StringToHash 并生成 C# 枚举</para>
    ///     <para>生成结果固定为 CFramework.AudioGroup 枚举，与框架音频系统绑定</para>
    ///     <para>使用：菜单 CFramework > Generate > AudioGroup Enum</para>
    /// </summary>
    public class AudioGroupGeneratorWindow : EditorWindow
    {
        // 固定枚举元数据，框架契约不可更改
        private const string FixedNamespace = "CFramework";
        private const string FixedEnumName = "AudioGroup";
        private const string FixedFileHeader = "/// <auto-generated />\n" +
                                               "/// 本文件由 AudioGroupGenerator 自动生成，请勿手动修改\n" +
                                               "/// {0}\n" +
                                               "/// AudioMixer：{1}\n";

        private AudioMixer _mixer;
        private string _outputPath = "Assets/AudioGroup.cs";
        private bool _autoDefineSymbol = true;
        private Vector2 _scroll;
        private List<GroupInfo> _previewGroups = new();
        private bool _previewDirty = true;

        private struct GroupInfo
        {
            /// <summary>Group 完整路径（用于 Description 和 Hash 计算）</summary>
            public string Path;
            /// <summary>Animator.StringToHash(Path)</summary>
            public int Hash;
            /// <summary>枚举成员名（仅 Group 自身名称，不含层级路径）</summary>
            public string MemberName;
        }

        [MenuItem("CFramework/Generate/AudioGroup Enum", priority = 100)]
        public static void ShowWindow()
        {
            var window = GetWindow<AudioGroupGeneratorWindow>("AudioGroup 生成器");
            window.minSize = new Vector2(400, 280);
            window.Show();
        }

        private void OnEnable()
        {
            var lastMixer = EditorPrefs.GetString("CFramework_AudioGroup_Mixer", "");
            if (!string.IsNullOrEmpty(lastMixer))
                _mixer = AssetDatabase.LoadAssetAtPath<AudioMixer>(lastMixer);

            _outputPath = EditorPrefs.GetString("CFramework_AudioGroup_Output", _outputPath);
            _autoDefineSymbol = EditorPrefs.GetBool("CFramework_AudioGroup_AutoDefine", true);
        }

        private void OnGUI()
        {
            EditorGUILayout.Space(8);
            EditorGUILayout.LabelField("AudioGroup 枚举自动生成", EditorStyles.boldLabel);

            EditorGUILayout.HelpBox(
                "读取 AudioMixer 中的所有 Group 路径，自动计算 Animator.StringToHash 并生成 C# 枚举。\n\n" +
                "生成的 AudioGroup 枚举附带扩展方法 ToPath()，可直接传给音频系统接口。\n" +
                "每次修改 Mixer 路径后需重新生成。",
                MessageType.Info);

            EditorGUILayout.Space(4);
            EditorGUILayout.LabelField("配置", EditorStyles.boldLabel);

            // 选择 AudioMixer
            EditorGUI.BeginChangeCheck();
            _mixer = (AudioMixer)EditorGUILayout.ObjectField("AudioMixer", _mixer, typeof(AudioMixer), false);
            if (EditorGUI.EndChangeCheck())
            {
                _previewDirty = true;
                if (_mixer != null)
                    EditorPrefs.SetString("CFramework_AudioGroup_Mixer", AssetDatabase.GetAssetPath(_mixer));
            }

            // 输出路径（唯一可配置项）
            EditorGUILayout.BeginHorizontal();
            EditorGUI.BeginChangeCheck();
            _outputPath = EditorGUILayout.TextField("输出路径", _outputPath);
            if (GUILayout.Button("浏览...", GUILayout.Width(60)))
            {
                var selected = EditorUtility.SaveFilePanelInProject(
                    "选择输出路径",
                    "AudioGroup.cs",
                    "cs",
                    "选择 AudioGroup.cs 的输出路径");
                if (!string.IsNullOrEmpty(selected))
                {
                    _outputPath = selected;
                    _previewDirty = true;
                }
            }
            EditorGUILayout.EndHorizontal();
            if (EditorGUI.EndChangeCheck())
                EditorPrefs.SetString("CFramework_AudioGroup_Output", _outputPath);

            // 显示固定信息
            EditorGUI.BeginDisabledGroup(true);
            EditorGUILayout.TextField("命名空间", FixedNamespace);
            EditorGUILayout.TextField("枚举名", FixedEnumName);
            EditorGUI.EndDisabledGroup();

            // 宏定义开关
            EditorGUI.BeginChangeCheck();
            _autoDefineSymbol = EditorGUILayout.Toggle(
                new GUIContent("自动注册 CFRAMEWORK_AUDIO 宏",
                    "生成枚举的同时，在项目的 Scripting Define Symbols 中注册 CFRAMEWORK_AUDIO 宏定义。"),
                _autoDefineSymbol);
            if (EditorGUI.EndChangeCheck())
                EditorPrefs.SetBool("CFramework_AudioGroup_AutoDefine", _autoDefineSymbol);

            // 宏定义操作按钮
            EditorGUILayout.BeginHorizontal();
            if (GUILayout.Button("注册宏定义", GUILayout.Width(100)))
            {
                DefineSymbol("CFRAMEWORK_AUDIO");
                EditorUtility.DisplayDialog("宏定义", "CFRAMEWORK_AUDIO 宏定义已注册", "确定");
            }
            if (GUILayout.Button("取消注册宏定义", GUILayout.Width(110)))
            {
                UndefineSymbol("CFRAMEWORK_AUDIO");
                EditorUtility.DisplayDialog("宏定义", "CFRAMEWORK_AUDIO 宏定义已取消注册", "确定");
            }
            GUILayout.FlexibleSpace();
            EditorGUILayout.EndHorizontal();

            EditorGUILayout.Space(8);
            EditorGUILayout.LabelField("预览", EditorStyles.boldLabel);

            if (_mixer != null)
            {
                if (_previewDirty)
                {
                    _previewGroups = CollectGroups(_mixer);
                    _previewDirty = false;
                }

                using (var scroll = new EditorGUILayout.ScrollViewScope(_scroll, GUILayout.Height(140)))
                {
                    _scroll = scroll.scrollPosition;
                    foreach (var g in _previewGroups)
                    {
                        EditorGUILayout.LabelField($"  {g.Path}", $"= {g.Hash}");
                    }
                }

                EditorGUILayout.HelpBox($"共 {_previewGroups.Count} 个 Group", MessageType.None);
            }
            else
            {
                EditorGUILayout.HelpBox("请先指定 AudioMixer", MessageType.Warning);
            }

            EditorGUILayout.Space(8);

            // 生成按钮
            GUI.enabled = _mixer != null && !string.IsNullOrWhiteSpace(_outputPath);
            if (GUILayout.Button("生成 AudioGroup.cs", GUILayout.Height(30)))
            {
                Generate(_mixer, _outputPath, _autoDefineSymbol);
            }
            GUI.enabled = true;

            EditorGUILayout.Space(4);
            if (GUILayout.Button("在文件夹中打开", GUILayout.Height(22)))
            {
                if (File.Exists(_outputPath))
                    EditorUtility.RevealInFinder(_outputPath);
            }
        }

        /// <summary>
        ///     从 AudioMixer 收集所有 Group 路径
        ///     <para>
        ///         通过 SerializedObject 遍历 Mixer 内部 Group 树：
        ///         1. mixer SerializedObject.FindProperty("m_MasterGroup") 获取根 Group
        ///         2. 对 Group 对象创建 SerializedObject，访问 m_Name / m_Children
        ///         3. 递归 m_Children 数组构建完整路径
        ///     </para>
        /// </summary>
        private static List<GroupInfo> CollectGroups(AudioMixer mixer)
        {
            var mixerSerialized = new SerializedObject(mixer);
            var masterProp = mixerSerialized.FindProperty("m_MasterGroup");
            var groups = new List<GroupInfo>();
            CollectChildGroups(masterProp, "", groups);
            return groups;
        }

        /// <summary>
        ///     递归收集子 Group
        /// </summary>
        private static void CollectChildGroups(SerializedProperty groupProp, string parentPath, List<GroupInfo> groups)
        {
            // 跳过无效引用
            if (groupProp == null || groupProp.objectReferenceValue == null)
                return;

            // 通过 objectReferenceValue 创建 Group 自己的 SerializedObject
            var groupSerialized = new SerializedObject(groupProp.objectReferenceValue);
            var nameProp = groupSerialized.FindProperty("m_Name");
            var name = nameProp?.stringValue ?? "";

            if (string.IsNullOrEmpty(name))
                return;

            var fullPath = string.IsNullOrEmpty(parentPath) ? name : $"{parentPath}/{name}";
            groups.Add(new GroupInfo
            {
                Path = fullPath,
                Hash = Animator.StringToHash(fullPath),
                // 枚举成员名仅用 Group 自身名称，层级信息由 Description 标注
                MemberName = name
            });

            // 递归子 Group
            var childrenProp = groupSerialized.FindProperty("m_Children");
            if (childrenProp != null && childrenProp.isArray)
            {
                for (int i = 0; i < childrenProp.arraySize; i++)
                {
                    CollectChildGroups(childrenProp.GetArrayElementAtIndex(i), fullPath, groups);
                }
            }
        }

        /// <summary>
        ///     在项目的 Scripting Define Symbols 中注册指定宏定义
        /// </summary>
        private static void DefineSymbol(string symbol)
        {
            var buildTarget = EditorUserBuildSettings.activeBuildTarget;
            var group = BuildPipeline.GetBuildTargetGroup(buildTarget);
            var defines = PlayerSettings.GetScriptingDefineSymbolsForGroup(group);

            if (defines.Contains(symbol))
                return; // 已存在，跳过

            PlayerSettings.SetScriptingDefineSymbolsForGroup(group, $"{defines};{symbol}");
        }

        /// <summary>
        ///     取消注册指定宏定义
        /// </summary>
        private static void UndefineSymbol(string symbol)
        {
            var buildTarget = EditorUserBuildSettings.activeBuildTarget;
            var group = BuildPipeline.GetBuildTargetGroup(buildTarget);
            var defines = PlayerSettings.GetScriptingDefineSymbolsForGroup(group);

            if (!defines.Contains(symbol))
                return; // 不存在，跳过

            var parts = defines.Split(';');
            var newDefines = new List<string>();
            foreach (var part in parts)
            {
                if (part.Trim() != symbol)
                    newDefines.Add(part.Trim());
            }

            PlayerSettings.SetScriptingDefineSymbolsForGroup(group, string.Join(";", newDefines));
        }

        /// <summary>
        ///     检查指定宏定义是否已注册
        /// </summary>
        private static bool HasSymbol(string symbol)
        {
            var buildTarget = EditorUserBuildSettings.activeBuildTarget;
            var group = BuildPipeline.GetBuildTargetGroup(buildTarget);
            var defines = PlayerSettings.GetScriptingDefineSymbolsForGroup(group);
            return defines.Contains(symbol);
        }

        /// <summary>
        ///     生成 AudioGroup.cs 枚举文件
        /// </summary>
        /// <param name="mixer">AudioMixer 资源</param>
        /// <param name="outputPath">输出文件路径</param>
        /// <param name="autoDefineSymbol">是否自动在项目中注册 CFRAMEWORK_AUDIO 宏定义</param>
        public static void Generate(AudioMixer mixer, string outputPath, bool autoDefineSymbol)
        {
            var groups = CollectGroups(mixer);

            if (groups.Count == 0)
            {
                EditorUtility.DisplayDialog("AudioGroup 生成器", "未在 AudioMixer 中找到任何 Group", "确定");
                return;
            }

            var sb = new StringBuilder();
            var timestamp = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
            var mixerPath = AssetDatabase.GetAssetPath(mixer);
            sb.AppendFormat(FixedFileHeader, $"生成时间：{timestamp}", mixerPath);
            sb.AppendLine();
            sb.AppendLine("#if CFRAMEWORK_AUDIO");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.ComponentModel;");
            sb.AppendLine();
            sb.AppendLine($"namespace {FixedNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    ///     音频分组枚举");
            sb.AppendLine("    ///     <para>值 = Animator.StringToHash(Group路径)，用于运行时 O(1) 查找</para>");
            sb.AppendLine("    ///     <para>对应 AudioMixer 的 Group 层级</para>");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public enum {FixedEnumName}");
            sb.AppendLine("    {");

            for (int i = 0; i < groups.Count; i++)
            {
                var g = groups[i];
                sb.AppendLine($"        [Description(\"{g.Path}\")]");
                sb.AppendLine($"        {g.MemberName} = {g.Hash}{(i < groups.Count - 1 ? "," : "")}");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    ///     路径查找表（Group 哈希 → 路径字符串）");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    internal static class AudioGroupPaths");
            sb.AppendLine("    {");
            sb.AppendLine("        private static readonly Dictionary<int, string> _map = new();");
            sb.AppendLine("        private static bool _initialized;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>根据哈希值查找路径（O(1)）</summary>");
            sb.AppendLine("        internal static string GetPath(int hash)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (!_initialized)");
            sb.AppendLine("            {");
            sb.AppendLine("                _initialized = true;");
            foreach (var g in groups)
                sb.AppendLine($"                _map[{g.Hash}] = \"{g.Path}\";");
            sb.AppendLine("            }");
            sb.AppendLine("            return _map.TryGetValue(hash, out var path) ? path : null;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    ///     AudioGroup 扩展方法 —— 将枚举值转为路径字符串，供 CFramework 音频系统使用");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class AudioGroupExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>枚举值 → Group 路径字符串（用于 IAudioService）</summary>");
            sb.AppendLine("        public static string ToPath(this AudioGroup group) => AudioGroupPaths.GetPath((int)group);");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#endif");

            // 确保目录存在
            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();

            // 注册宏定义
            if (autoDefineSymbol)
                DefineSymbol("CFRAMEWORK_AUDIO");

            EditorUtility.DisplayDialog(
                "生成成功",
                $"已生成 {groups.Count} 个枚举成员：\n{outputPath}" +
                (autoDefineSymbol ? "\n\n已注册 CFRAMEWORK_AUDIO 宏定义。" : ""),
                "确定");

            EditorGUIUtility.PingObject(AssetDatabase.LoadAssetAtPath<TextAsset>(outputPath));
        }
    }
}
#endif
