using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using CFramework.Editor.Configs;
using UnityEditor;
using UnityEngine;

namespace CFramework.Editor.Generators
{
    /// <summary>
    ///     UI 面板代码生成器
    ///     <para>读取 UIBinder 中手动配置的组件数据 → 生成 IUI 绑定代码</para>
    /// </summary>
    public static class UIPanelGenerator
    {
        #region 公开方法

        /// <summary>
        ///     一键生成：读取 UIBinder 配置 → 生成绑定代码
        /// </summary>
        /// <param name="binder">UIBinder 实例</param>
        /// <param name="prefabName">Prefab 名称（用作类名）</param>
        public static void Generate(UIBinder binder, string prefabName)
        {
            var components = binder.Components;
            if (components == null || components.Length == 0)
            {
                Debug.LogWarning($"[UIPanelGenerator] UIBinder 中没有配置任何组件: {prefabName}");
                return;
            }

            // 1. 生成绑定代码
            EditorPaths.EnsureDirectoryExists(UIPanelGeneratorConfig.OutputPath);
            GenerateBindingCode(prefabName, components);

            // 2. 可选：生成用户骨架文件
            if (UIPanelGeneratorConfig.GenerateUserFile) GenerateUserCode(prefabName);

            AssetDatabase.Refresh();
            Debug.Log($"[UIPanelGenerator] 生成完成: {prefabName}，共 {components.Length} 个组件");
        }

        #endregion

        #region 命名转换

        /// <summary>
        ///     将物体名称转换为字段名（统一 _camelCase 风格）
        ///     <para>移除常见前缀后转驼峰</para>
        /// </summary>
        private static string ToFieldName(string name)
        {
            if (string.IsNullOrEmpty(name)) return name;

            // 移除常见 UI 前缀
            name = Regex.Replace(name, @"^(m_|btn_|txt_|img_|go_|obj_)", "", RegexOptions.IgnoreCase);

            // 下划线分隔 → 驼峰
            if (name.Contains("_"))
            {
                var parts = name.Split(new[] { '_' }, StringSplitOptions.RemoveEmptyEntries);
                var sb = new StringBuilder();
                for (var i = 0; i < parts.Length; i++)
                    if (i == 0)
                        sb.Append(char.ToLower(parts[i][0]) + parts[i].Substring(1));
                    else
                        sb.Append(char.ToUpper(parts[i][0]) + parts[i].Substring(1).ToLower());

                return sb.ToString();
            }

            return char.ToLower(name[0]) + name.Substring(1);
        }

        #endregion

        #region 文件写入

        private static void WriteToFile(string filePath, string code)
        {
            var directory = Path.GetDirectoryName(filePath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory)) Directory.CreateDirectory(directory);

            File.WriteAllText(filePath, code, Encoding.UTF8);
        }

        #endregion

        #region 内部类型

        private struct FieldInfo
        {
            public int Index;
            public string TypeName;
            public string FieldName;
            public string DisplayName;
        }

        #endregion

        #region 常量

        private const string AutoGeneratedHeader =
            "// <auto-generated>\n" +
            "//     此代码由 CFramework UIPanelGenerator 自动生成。\n" +
            "//     对此文件的更改可能导致错误的行为，并且会在重新生成时丢失。\n" +
            "// </auto-generated>\n\n";

        /// <summary>
        ///     不需要自动引用的命名空间（全局命名空间或目标命名空间自身）
        /// </summary>
        private static readonly HashSet<string> IgnoredNamespaces = new()
        {
            "",                      // 全局命名空间
            "UI"                     // 目标命名空间，已通过 namespace 声明包含
        };

        #endregion

        #region 代码生成

        /// <summary>
        ///     生成绑定代码文件
        /// </summary>
        private static void GenerateBindingCode(string prefabName, UIComponent[] components)
        {
            // 收集组件信息
            var fields = new List<FieldInfo>();
            var usings = new HashSet<string> { "using CFramework;" };

            for (var i = 0; i < components.Length; i++)
            {
                var comp = components[i];
                if (comp.ComponentType == null || comp.gameObject == null) continue;

                var typeName = comp.ComponentType.Name;
                var ns = comp.ComponentType.Namespace;

                // 收集 using 指令（跳过全局命名空间和目标命名空间）
                if (!string.IsNullOrEmpty(ns) && !IgnoredNamespaces.Contains(ns))
                    usings.Add($"using {ns};");

                var fieldName = ToFieldName(comp.Name);

                fields.Add(new FieldInfo
                {
                    Index = i,
                    TypeName = typeName,
                    FieldName = fieldName,
                    DisplayName = comp.Name
                });
            }

            // 构建代码
            var sb = new StringBuilder();
            sb.Append(AutoGeneratedHeader);

            foreach (var use in usings.OrderBy(u => u)) sb.AppendLine(use);

            sb.AppendLine();
            sb.AppendLine($"namespace {UIPanelGeneratorConfig.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {prefabName}");
            sb.AppendLine("    {");

            // 生成字段
            for (var i = 0; i < fields.Count; i++)
            {
                var field = fields[i];

                if (UIPanelGeneratorConfig.GenerateXmlComments)
                {
                    sb.AppendLine("        /// <summary>");
                    sb.AppendLine($"        /// {field.DisplayName}");
                    sb.AppendLine("        /// </summary>");
                }

                sb.AppendLine(
                    $"        private {field.TypeName} {UIPanelGeneratorConfig.FieldPrefix}{field.FieldName};");

                if (i < fields.Count - 1) sb.AppendLine();
            }

            sb.AppendLine();
            sb.AppendLine("        void IUI.InjectUI(UIBinder binder)");
            sb.AppendLine("        {");

            // 生成赋值语句
            foreach (var field in fields)
                sb.AppendLine(
                    $"            {UIPanelGeneratorConfig.FieldPrefix}{field.FieldName} = binder.Get<{field.TypeName}>({field.Index});");

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            // 写入文件
            var fileName = $"{prefabName}{UIPanelGeneratorConfig.BindingsFileSuffix}";
            var filePath = Path.Combine(UIPanelGeneratorConfig.OutputPath, fileName);
            WriteToFile(filePath, sb.ToString());
        }

        /// <summary>
        ///     生成用户骨架文件（仅首次，不覆盖已有文件）
        /// </summary>
        private static void GenerateUserCode(string prefabName)
        {
            var fileName = $"{prefabName}{UIPanelGeneratorConfig.UserFileSuffix}";
            var filePath = Path.Combine(UIPanelGeneratorConfig.OutputPath, fileName);

            if (File.Exists(filePath)) return;

            var sb = new StringBuilder();
            sb.AppendLine("using CFramework;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine($"namespace {UIPanelGeneratorConfig.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {prefabName} : IUI");
            sb.AppendLine("    {");
            sb.AppendLine("        public void OnCreate()");
            sb.AppendLine("        {");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public void OnShow()");
            sb.AppendLine("        {");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public void OnHide()");
            sb.AppendLine("        {");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public void OnDestroy()");
            sb.AppendLine("        {");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            WriteToFile(filePath, sb.ToString());
        }

        #endregion
    }
}